# Generated by Django 3.1.2 on 2020-10-29 17:46

import Auth_app.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolio', models.URLField(blank=True)),
                ('image', models.ImageField(upload_to='profile_pic')),
                ('user', models.OneToOneField(on_delete=Auth_app.models.on_delete, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
